version: '3'

services:
  master:
    image: spark-hadoop-img-ssh
    container_name: hadoop-master
    ports:
       - 8088:8088
       - 8042:8042
       - 4040:4040
       - 7077:7077
       - 50070:50070
       - 9001:9001
       - 50010:50010
    volumes:
        - ./prog-files/hadoop:/usr/local/hadoop
        - ./prog-files/spark:/usr/local/spark
    environment:
        - JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
        - HADOOP_HOME=/usr/local/hadoop
        - SPARK_HOME=/usr/local/spark
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HADOOP_HOME/bin:$SPARK_HOME/bin:/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin
        - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        - HDFS_NAMENODE_USER=root
        - HDFS_DATANODE_USER=root
        - HDFS_SECONDARYNAMENODE_USER=root
        - YARN_RESOURCEMANAGER_USER=root
        - YARN_NODEMANAGER_USER=root
        - HADOOP_SSH_OPTS=-p 22
    tty: true
  slave1:
    image: spark-hadoop-img-ssh
    container_name: hadoop-slave1
    ports:
      - 9000:9000
      - 9870:9870
    volumes:
        - ./prog-files-1/hadoop:/usr/local/hadoop
    environment:
        - JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
        - HADOOP_HOME=/usr/local/hadoop
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HADOOP_HOME/bin:/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin
        - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        - HDFS_NAMENODE_USER=root
        - HDFS_DATANODE_USER=root
        - HDFS_SECONDARYNAMENODE_USER=root
        - YARN_RESOURCEMANAGER_USER=root
        - YARN_NODEMANAGER_USER=root
        - HADOOP_SSH_OPTS=-p 22
    tty: true
  slave2:
    image: spark-hadoop-img-ssh
    container_name: hadoop-slave2
    volumes:
        - ./prog-files-2/hadoop:/usr/local/hadoop
    environment:
        - JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
        - HADOOP_HOME=/usr/local/hadoop
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HADOOP_HOME/bin:/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin
        - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        - HDFS_NAMENODE_USER=root
        - HDFS_DATANODE_USER=root
        - HDFS_SECONDARYNAMENODE_USER=root
        - YARN_RESOURCEMANAGER_USER=root
        - YARN_NODEMANAGER_USER=root
        - HADOOP_SSH_OPTS=-p 22
    tty: true
